gravity_compensation_controller2:
  type: open_manipulator_controllers/GravityCompensationController
  joint_names:
    - arm2_joint1
    - arm2_joint2
    - arm2_joint3
    - arm2_joint4
    - arm2_virtual_roll_joint
    - arm2_virtual_yaw_joint

  root_link: world
  tip_link: end_effector_link
