arm2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm2_joint1
    - arm2_joint2
    - arm2_joint3
    - arm2_joint4
    - arm2_virtual_roll_joint
    - arm2_virtual_yaw_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      joint1: {trajectory: 0.1, goal: 0.1}
      joint2: {trajectory: 0.1, goal: 0.1}
      joint3: {trajectory: 0.1, goal: 0.1}
      joint4: {trajectory: 0.1, goal: 0.1}
      virtual_roll_joint: {trajectory: 0.1, goal: 0.1}
      virtual_yaw_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

