# MoveIt-specific simulation settings
# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: zero

# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - gripper
    - virtual_roll_joint
    - virtual_yaw_joint
  sim_control_mode: 2  # 2: effort control for gravity compensation

# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Gravity compensation controller for effort-based control
effort_controllers:
  - name: gravity_compensation_controller
    type: effort_controllers/JointEffortController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - virtual_roll_joint
      - virtual_yaw_joint
    pid_gains:
      joint1: {p: 1.0, i: 0.0, d: 0.0}
      joint2: {p: 1.0, i: 0.0, d: 0.0}
      joint3: {p: 1.0, i: 0.0, d: 0.0}
      joint4: {p: 1.0, i: 0.0, d: 0.0}
      virtual_roll_joint: {p: 1.0, i: 0.0, d: 0.0}
      virtual_yaw_joint: {p: 1.0, i: 0.0, d: 0.0}

# FollowJointTrajectory controller for regular joint motion
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - virtual_roll_joint
      - virtual_yaw_joint

