# MoveIt-specific simulation settings
# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: zero

# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - arm2_joint1
    - arm2_joint2
    - arm2_joint3
    - arm2_joint4
    - arm2_gripper
    - arm2_virtual_roll_joint
    - arm2_virtual_yaw_joint
  sim_control_mode: 2  # 2: effort control for gravity compensation

# Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Gravity compensation controller using effort control
effort_controllers:
  - name: gravity_compensation_controller
    type: effort_controllers/JointEffortController
    joints:
      - arm2_joint1
      - arm2_joint2
      - arm2_joint3
      - arm2_joint4
      - arm2_virtual_roll_joint
      - arm2_virtual_yaw_joint
    pid_gains:
      arm2_joint1: {p: 1.0, i: 0.0, d: 0.0}
      arm2_joint2: {p: 1.0, i: 0.0, d: 0.0}
      arm2_joint3: {p: 1.0, i: 0.0, d: 0.0}
      arm2_joint4: {p: 1.0, i: 0.0, d: 0.0}
      arm2_virtual_roll_joint: {p: 1.0, i: 0.0, d: 0.0}
      arm2_virtual_yaw_joint: {p: 1.0, i: 0.0, d: 0.0}

